### ISSUE TITLE
WHMCS API details missing

### ISSUE THREAD

**Issue by a945116826** [bsbudhwar/Freeradius-Module-WHMCS#2]
Who can help me

**Comment by bsbudhwar** [comment]
What kind of help you want...?

**Comment by a945116826** [comment]
I want to buy Whmcs-Freeradius module，What is the price if I buy the code.

bsbudhwar <notifications@github.com> 于2020年12月1日周二 下午11:05写道：

**Comment by bsbudhwar** [comment]
I am not encrypting the source code. It's one time  purchase cost is 120 USD with 6 months code update and after that if any issue then chargeable per incident bases.
